/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.text.StyledEditorKit.ForegroundAction;

import control.Controlador;
import control.Observator;
import control.ObservatorClases;
import datos.Producto;
import datos.Valoracion;

/**
 *
 * @author usuario_local
 */
public class Diseno extends JFrame implements ObservatorClases {

	private javax.swing.JButton botonLogin;
	private javax.swing.JButton BotonPerfil;
	private javax.swing.JButton botonComprar;
	private javax.swing.JButton botonAnadirCesta;
	private javax.swing.JButton jButton5;
	private javax.swing.JComboBox<String> jComboBox1;
	private javax.swing.JDialog jDialog1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JList<String> listaProductos;
	private javax.swing.JList<String> jList2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JRadioButton jRadioButton4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTextArea informacion;
	private javax.swing.JTextArea textoValoraciones;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JToggleButton jToggleButton1;

	private boolean usuarioLogueado;

	private Login login = new Login(this);
	private InfoUsuario infoUsuario;

	private ArrayList<Producto> productosMostrados;
	private ArrayList<Valoracion> valoracionesMostradas;
	DefaultListModel modelo;

	/**
	 * Creates new form Diseño
	 */
	public Diseno() {
		initComponents();
		
		Controlador.getInstance().addObservador(this);
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		modelo = new DefaultListModel<>();
		jDialog1 = new javax.swing.JDialog();
		jPanel1 = new javax.swing.JPanel();
		botonLogin = new javax.swing.JButton();
		BotonPerfil = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jToggleButton1 = new javax.swing.JToggleButton();
		jComboBox1 = new javax.swing.JComboBox<>();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jRadioButton4 = new javax.swing.JRadioButton();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		listaProductos = new javax.swing.JList<>();
		jScrollPane3 = new javax.swing.JScrollPane();
		jList2 = new javax.swing.JList<>();
		jLabel4 = new javax.swing.JLabel();
		botonComprar = new javax.swing.JButton();
		botonAnadirCesta = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		informacion = new javax.swing.JTextArea();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane4 = new javax.swing.JScrollPane();
		textoValoraciones = new javax.swing.JTextArea();
		jLabel6 = new javax.swing.JLabel();

		javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(
				jDialog1.getContentPane());
		jDialog1.getContentPane().setLayout(jDialog1Layout);
		jDialog1Layout.setHorizontalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		
		botonLogin.setText("Login");
		botonLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botonLoginActionPerformed(evt);
			}
		});

		BotonPerfil.setText("Perfil");
		BotonPerfil.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				if(usuarioLogueado)infoUsuario.setVisible(true);
				else JOptionPane.showMessageDialog(null,
						"Debes loguearte para ver la informacion");
				
			}
		});

		jLabel1.setFont(new java.awt.Font("Trajan Pro", 3, 14)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("EZ GAMES");

		jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
		jTextField1.setName(""); // NOI18N
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});
		jToggleButton1.setName("Buscar");
		jToggleButton1.setIcon(new ImageIcon("resources/guardar.jpg"));

		jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton1ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "PC", "PS4", "XONE", "Switch" }));
		jComboBox1.setToolTipText("");

		jRadioButton1.setText("PC");
		jRadioButton1.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				jRadioButton2.setSelected(false);
				jRadioButton3.setSelected(false);
				jRadioButton4.setSelected(false);
				Controlador.getInstance().obtenerProductosPlataforma("PC");

			}
		});

		jRadioButton2.setText("PS4");
		jRadioButton2.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				jRadioButton1.setSelected(false);
				jRadioButton3.setSelected(false);
				jRadioButton4.setSelected(false);
				Controlador.getInstance().obtenerProductosPlataforma("PS4");

			}
		});

		jRadioButton3.setText("XONE");
		jRadioButton3.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				jRadioButton1.setSelected(false);
				jRadioButton2.setSelected(false);
				jRadioButton4.setSelected(false);
				Controlador.getInstance().obtenerProductosPlataforma("XBOXONE");

			}
		});

		jRadioButton4.setText("Switch");
		jRadioButton4.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				jRadioButton1.setSelected(false);
				jRadioButton2.setSelected(false);
				jRadioButton3.setSelected(false);
				Controlador.getInstance().obtenerProductosPlataforma("Switch");

			}
		});

		jLabel2.setText("Seleccione plataforma:");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel3.setText("Resultados de la búsqueda");
		jLabel3.setToolTipText("");

		listaProductos.setModel(new javax.swing.AbstractListModel<String>() {
			String[] strings = {};

			public int getSize() {
				return strings.length;
			}

			public String getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane2.setViewportView(listaProductos);

		jList2.setModel(new javax.swing.AbstractListModel<String>() {
			String[] strings = {};

			public int getSize() {
				return strings.length;
			}

			public String getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane3.setViewportView(jList2);

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
		jLabel4.setText("Cesta");

		botonComprar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		botonComprar.setText("¡Confirmar compra!");
		botonComprar.setToolTipText("");
		botonComprar.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				if(!usuarioLogueado) JOptionPane.showMessageDialog(null,"Debes iniciar sesion para comprar");
				else {
					JOptionPane.showMessageDialog(null,"Compra realizada con exito");
				}
				
			}
		});

		botonAnadirCesta.setText("Añadir a cesta >>");
		botonAnadirCesta.setName("anadirCesta"); // NOI18N
		botonAnadirCesta.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				anadirCompra(listaProductos.getSelectedValue());
				
			}
		});

		jButton5.setText("<< Quitar de cesta");
		jButton5.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				eliminarCompra(jList2.getSelectedValue());
				
			}
		});
		informacion.setColumns(20);
		informacion.setRows(5);
		jScrollPane1.setViewportView(informacion);

		jLabel5.setText("Información");

		textoValoraciones.setColumns(20);
		textoValoraciones.setRows(5);
		jScrollPane4.setViewportView(textoValoraciones);

		jLabel6.setText("Valoraciones");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jScrollPane2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				216,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addGap(0,
																																				0,
																																				Short.MAX_VALUE)
																																		.addGroup(
																																				jPanel1Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING,
																																								false)
																																						.addComponent(
																																								botonAnadirCesta,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								Short.MAX_VALUE)
																																						.addComponent(
																																								jButton5,
																																								javax.swing.GroupLayout.DEFAULT_SIZE,
																																								157,
																																								Short.MAX_VALUE))
																																		.addGap(61,
																																				61,
																																				61))
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				jPanel1Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addComponent(
																																								jScrollPane4,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								273,
																																								javax.swing.GroupLayout.PREFERRED_SIZE)
																																						.addComponent(
																																								jScrollPane1,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								273,
																																								javax.swing.GroupLayout.PREFERRED_SIZE))
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE))))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addGap(112,
																																				112,
																																				112)
																																		.addComponent(
																																				jLabel5))
																														.addGroup(
																																jPanel1Layout
																																		.createSequentialGroup()
																																		.addGap(121,
																																				121,
																																				121)
																																		.addComponent(
																																				jLabel6)))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)))
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								jScrollPane3)
																						.addComponent(
																								botonComprar,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								221,
																								Short.MAX_VALUE)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				BotonPerfil)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jToggleButton1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								38,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								botonLogin,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								85,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addContainerGap())))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(73, 73, 73)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(51,
																												51,
																												51)
																										.addComponent(
																												jLabel3)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												jLabel4))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jTextField1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												486,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												26,
																												Short.MAX_VALUE)
																										.addComponent(
																												jComboBox1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(91,
																				91,
																				91))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(11,
																				11,
																				11)
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				160,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jRadioButton1)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jRadioButton2)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jRadioButton3)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jRadioButton4)
																		.addGap(0,
																				0,
																				Short.MAX_VALUE)))));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																BotonPerfil,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																28,
																Short.MAX_VALUE)
														.addComponent(
																botonLogin,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addGap(41, 41, 41)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								37,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jComboBox1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								37,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(32,
																				32,
																				32)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								23,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jRadioButton1)
																						.addComponent(
																								jRadioButton2)
																						.addComponent(
																								jRadioButton3)
																						.addComponent(
																								jRadioButton4))
																		.addGap(23,
																				23,
																				23)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel4)))
														.addComponent(
																jToggleButton1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																38,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jScrollPane2)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jScrollPane3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				407,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				botonComprar,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				37,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(14,
																				14,
																				14)
																		.addComponent(
																				botonAnadirCesta)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jButton5)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jLabel5)
																		.addGap(2,
																				2,
																				2)
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				136,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(23,
																				23,
																				23)
																		.addComponent(
																				jLabel6)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jScrollPane4)))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void botonLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botonLoginActionPerformed

		if(!usuarioLogueado) login.setVisible(true);
		else {
			botonLogin.setText("Login");
			BotonPerfil.setText("Perfil");
			usuarioLogueado = false;
		}

	}// GEN-LAST:event_botonLoginActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton1ActionPerformed
		// TODO add your handling code here:
		System.out.println("buscando..." + jTextField1.getText());
		productosMostrados = Controlador.getInstance().buscarProducto(
				jTextField1.getText());
		if (!productosMostrados.isEmpty()) {
			actualizarLista(productosMostrados);
		}
	}// GEN-LAST:event_jToggleButton1ActionPerformed

	
	private void anadirCompra(String compra) {
		modelo.addElement(compra);
		jList2.setModel(modelo);
	}
	private void eliminarCompra(String compra) {
		modelo.removeElement(compra);
		jList2.setModel(modelo);
	}
	
	private void actualizarLista(ArrayList<Producto> p2) {
		// TODO Auto-generated method stub
		String[] str = new String[p2.size()];
		for (int i = 0; i < p2.size(); i++) {
			str[i] = p2.get(i).get_nombre();
		}
		str.clone();
		listaProductos.setModel(new javax.swing.AbstractListModel<String>() {
			String[] strings = str.clone();

			public int getSize() {
				return strings.length;
			}

			public String getElementAt(int i) {
				return strings[i];
			}
		});
		/*informacion.setText("Precio:\t" + p2.get(0).get_nombre() + "\n"
				+ "Plataforma:\t" + p2.get(0).get_genero() + "\nPrecio:\t"
				+ Double.toString(p2.get(0).get_precio()));*/
		listaProductos.addListSelectionListener(new ListSelectionListener() {

			@Override
			public void valueChanged(ListSelectionEvent e) {
				if (!e.getValueIsAdjusting()) {
					informacion.setText(obtenerInfo(listaProductos.getSelectedValue().toString()));
					textoValoraciones.setText(obtenerValoraciones(listaProductos.getSelectedValue().toString()));
					
				}

			}
		});
	}
	protected String obtenerValoraciones(String string) {
		String devolver = "";
		for(int i=0; i<productosMostrados.size();i++) {
			if(productosMostrados.get(i).get_nombre().equalsIgnoreCase(string)) {
				for(int j=0; j<valoracionesMostradas.size();j++) {
					if(productosMostrados.get(i).get_id().equalsIgnoreCase(valoracionesMostradas.get(j).get_producto())) {
						devolver += valoracionesMostradas.get(j).get_usuario() + ": " + valoracionesMostradas.get(j).get_texto()+"\n"; 
					}
				}
				break;
			}
		}
		return devolver;
	}

	private String obtenerInfo(String producto) {
		for(int i=0; i<productosMostrados.size();i++) {
			if(productosMostrados.get(i).get_nombre().equalsIgnoreCase(producto)) {
				return "Plataforma: "+productosMostrados.get(i).get_genero()+"\nPrecio: "+productosMostrados.get(i).get_precio()+"\nStock: "+productosMostrados.get(i).get_stock();
			}
		}
		return null;
	}

	@Override
	public void login(String nombre,String apellido, String correo, String tipo) {
		BotonPerfil.setText(nombre);
		infoUsuario = new InfoUsuario(nombre, apellido, correo, tipo);
		botonLogin.setText("Logout");
		usuarioLogueado = true;
	}

	@Override
	public void busqueda(ArrayList<Producto> p) {
		productosMostrados = p;
		actualizarLista(p);

	}

	@Override
	public void valoraciones(ArrayList<Valoracion> v) {
		this.valoracionesMostradas = v;
		
	}
}
